# Generated by Django 6.0.4 on 2026-04-25 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('enunciado', models.CharField(max_length=200)),
                ('respondida', models.BooleanField(default=False)),
            ],
        ),
    ]
