# Generated by Django 5.2.5 on 2026-04-27 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nossoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='dificuldade',
            field=models.CharField(choices=[('N', 'Nenhuma'), ('F', 'Fácil'), ('M', 'Médio'), ('D', 'Difícil')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='questao',
            name='materia',
            field=models.CharField(choices=[('NEN', 'Nenhuma'), ('MAT', 'Matemática'), ('LIN', 'Linguagens'), ('HUM', 'Ciências Humanas'), ('NAT', 'Ciências Naturais')], default='NEN', max_length=3),
        ),
        migrations.AlterField(
            model_name='questao',
            name='enunciado',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='questao',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
