# Generated by Django 5.2.5 on 2026-04-27 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nossoapp', '0002_questao_dificuldade_questao_materia_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questao',
            new_name='Questoes',
        ),
    ]
