# Generated by Django 5.2.5 on 2026-04-27 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nossoapp', '0004_alternativas_perfil_usuário'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternativas',
            name='letra',
            field=models.CharField(default='X', max_length=1),
        ),
        migrations.AlterField(
            model_name='alternativas',
            name='questao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternativas', to='nossoapp.questoes'),
        ),
    ]
