# Generated by Django 5.2.5 on 2026-04-27 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nossoapp', '0005_alternativas_letra_alter_alternativas_questao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativas',
            name='letra',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='alternativas',
            name='questao',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='alternativas', to='nossoapp.questoes'),
        ),
        migrations.AlterField(
            model_name='alternativas',
            name='texto',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='questoes',
            name='dificuldade',
            field=models.CharField(choices=[('F', 'Fácil'), ('M', 'Médio'), ('D', 'Difícil')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='questoes',
            name='materia',
            field=models.CharField(choices=[('MAT', 'Matemática'), ('LIN', 'Linguagens'), ('HUM', 'Ciências Humanas'), ('NAT', 'Ciências Naturais')], default='NEN', max_length=3),
        ),
    ]
