# Generated by Django 5.2.5 on 2026-04-27 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nossoapp', '0006_alter_alternativas_letra_alter_alternativas_questao_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='alternativas',
            constraint=models.UniqueConstraint(fields=('questao', 'letra'), name='letra_unica_por_questao'),
        ),
    ]
