# Generated by Django 5.2.5 on 2026-04-27 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nossoapp', '0007_alternativas_letra_unica_por_questao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil_usuário',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='questoes',
            name='respondida',
        ),
        migrations.AlterField(
            model_name='questoes',
            name='dificuldade',
            field=models.CharField(choices=[('F', 'Fácil'), ('M', 'Médio'), ('D', 'Difícil')], max_length=1),
        ),
        migrations.AlterField(
            model_name='questoes',
            name='materia',
            field=models.CharField(choices=[('MAT', 'Matemática'), ('LIN', 'Linguagens'), ('HUM', 'Ciências Humanas'), ('NAT', 'Ciências da Natureza')], max_length=3),
        ),
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letra', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1)),
                ('texto', models.TextField()),
                ('correta', models.BooleanField(default=False)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternativas', to='nossoapp.questoes')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RespostaUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternativa_escohida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nossoapp.alternativa')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nossoapp.questoes')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Alternativas',
        ),
        migrations.DeleteModel(
            name='Perfil_Usuário',
        ),
        migrations.AddConstraint(
            model_name='alternativa',
            constraint=models.UniqueConstraint(fields=('questao', 'letra'), name='letra_unica_por_questao'),
        ),
        migrations.AddConstraint(
            model_name='respostausuario',
            constraint=models.UniqueConstraint(fields=('usuario', 'questao'), name='resposta_unica_por_usuario'),
        ),
    ]
