# Generated by Django 5.2.5 on 2026-04-28 00:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nossoapp', '0008_remove_perfil_usuário_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questoes',
            name='ano',
            field=models.PositiveIntegerField(default=2026, validators=[django.core.validators.MinValueValidator(1998), django.core.validators.MaxValueValidator(2026)]),
        ),
        migrations.AlterField(
            model_name='alternativa',
            name='letra',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1, null=True),
        ),
    ]
