# Generated by Django 6.0.5 on 2026-05-07 04:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nossoapp', '0009_questoes_ano_alter_alternativa_letra'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos/')),
            ],
        ),
        migrations.CreateModel(
            name='QuestaoFeita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acertou', models.BooleanField(blank=True, null=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='usuario',
        ),
        migrations.RemoveConstraint(
            model_name='respostausuario',
            name='resposta_unica_por_usuario',
        ),
        migrations.RenameField(
            model_name='questoes',
            old_name='dificuldade',
            new_name='nivel',
        ),
        migrations.AlterField(
            model_name='alternativa',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='questoes',
            name='ano',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1998), django.core.validators.MaxValueValidator(2026)]),
        ),
        migrations.AlterField(
            model_name='questoes',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='estudantes',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questaofeita',
            name='alternativa_escolhida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nossoapp.alternativa'),
        ),
        migrations.AddField(
            model_name='questaofeita',
            name='questao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nossoapp.questoes'),
        ),
        migrations.AddField(
            model_name='questaofeita',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='PerfilUsuario',
        ),
        migrations.RemoveField(
            model_name='respostausuario',
            name='alternativa_escohida',
        ),
        migrations.RemoveField(
            model_name='respostausuario',
            name='questao',
        ),
        migrations.RemoveField(
            model_name='respostausuario',
            name='usuario',
        ),
        migrations.AddConstraint(
            model_name='questaofeita',
            constraint=models.UniqueConstraint(fields=('usuario', 'questao'), name='resposta_unica_por_usuario'),
        ),
        migrations.DeleteModel(
            name='RespostaUsuario',
        ),
    ]
