# Generated by Django 6.0.5 on 2026-05-16 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nossoapp', '0010_estudantes_questaofeita_remove_perfilusuario_usuario_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alternativa',
            options={'verbose_name': 'Alternativa', 'verbose_name_plural': 'Alternativas'},
        ),
        migrations.AlterModelOptions(
            name='estudantes',
            options={'verbose_name': 'Estudante', 'verbose_name_plural': 'Estudantes'},
        ),
        migrations.AlterModelOptions(
            name='questaofeita',
            options={'verbose_name': 'Questão Feita', 'verbose_name_plural': 'Questões Feitas'},
        ),
        migrations.AlterModelOptions(
            name='questoes',
            options={'verbose_name': 'Questão', 'verbose_name_plural': 'Questões'},
        ),
        migrations.RemoveConstraint(
            model_name='questaofeita',
            name='resposta_unica_por_usuario',
        ),
    ]
